### ISSUE TITLE
File putted to ftps server, but only 0KB

### ISSUE THREAD

**Issue by WinLordZ** [basilwong/azure-function-implicit-ftps-suite#2]
I have added 

```
   ftpsClient.execPBSZ(0);
            ftpsClient.execPROT("P");
            ftpsClient.setEnabledProtocols(new String[]{"TLSv1.2"});
            ftpsClient.enterLocalPassiveMode();
            ftpsClient.setBufferSize(1024 * 1024);
            ftpsClient.setDataTimeout(30000);
```

But reply code is

> INFO: 425 Unable to build data connection: TLS session of data connection not resumed.
And testOutput.txt is showed in folder of FTPS host, but it no data, only  0KB.

So do you have any idea to fix it?

**Comment by basilwong** [comment]
The error message `425 Unable to build data connection: TLS session of data connection not resumed` suggests that there is a problem with the TLS/SSL session resumption for the data connection in FTPS. This issue commonly occurs when the control connection and the data connection are not correctly negotiating the TLS session.

Here are some steps you can take to troubleshoot and resolve this issue:

1. Ensure FTPS Server Configuration:
Verify that the FTPS server supports TLS session resumption. Check the server configuration and documentation to ensure that it is correctly set up for TLS/SSL.
Check FTPS Client Configuration:

2. Ensure that the FTPS client is correctly configured to use TLS/SSL for both control and data connections. The settings in your code look mostly correct, but there might be additional configurations required.
Explicit vs Implicit FTPS:

3. Ensure that you are using the correct mode of FTPS (explicit or implicit). Most modern servers and clients use explicit FTPS. Ensure the server supports the mode you are using.

4. Passive Mode Issues:
Sometimes, passive mode can cause issues with data connections. You can try switching to active mode to see if it resolves the issue.

5. Firewall/Network Configuration:
Ensure that any firewalls or network configurations between the client and server allow for the necessary ports for the data connection. Passive mode requires a range of ports to be open.

6. Update FTPS Client Library:
Ensure that you are using the latest version of the FTPS client library. There might be bug fixes or improvements in newer versions that resolve your issue.

7. Debugging Information:
Enable detailed logging in the FTPS client to get more information about the connection process. This can provide more insights into what is going wrong.

*Here is a revised version of your code with additional logging:*

```
ftpsClient.addProtocolCommandListener(new PrintCommandListener(new PrintWriter(System.out), true));
ftpsClient.execPBSZ(0);
ftpsClient.execPROT("P");
ftpsClient.setEnabledProtocols(new String[]{"TLSv1.2"});
ftpsClient.enterLocalPassiveMode();
ftpsClient.setBufferSize(1024 * 1024);
ftpsClient.setDataTimeout(30000);
```

By adding the PrintCommandListener, you can see the commands being sent to and responses from the server, which might provide more clues about what is causing the problem.

If the problem persists after trying these steps, consider checking with the server administrator or support team for further assistance. They might be able to provide server-side logs that can help diagnose the issue.

**Comment by WinLordZ** [comment]
I checked all step which you recommend.
FTPS server config right, I can use WinSCP or FileZilla to upload or download file from it.
Network to run code and use winScp in same PC.
Library of FTPS client is org.apache.commons.net.ftp.FTPSClient lastest

I also have code to trace log call FTPS. This is full log

```
220-FileZilla Server 1.8.2
220 Please visit https://filezilla-project.org/
AUTH TLS
234 Using authentication type TLS.
PBSZ 0
200 PBSZ=0
PROT P
200 Protection level set to P
USER .....
331 Please, specify the password.
PASS .....
230 Login successful.
Login successful
TYPE I
200 Type set to I
CWD test_folder
250 CWD command successful
PWD
257 "/test_folder" is current directory.
Current working directory: /test_folder
Start uploading first file
PASV
227 Entering Passive Mode (10,21,32,6,196,250)
STOR test_signed.xml
150 Starting data transfer.
425 Unable to build data connection: TLS session of data connection not resumed.
Upload failed.
QUIT
221 Goodbye.
```

**Comment by basilwong** [comment]
The error `425 Unable to build data connection: TLS session of data connection not resumed` is often caused by issues with the TLS session resumption during the data connection setup. To address this issue, consider the following steps and code modifications:

1. **Enable Detailed Logging**: To get more insight into the problem, enable detailed logging for the FTP client.

2. **Verify Server Configuration**: Ensure that the server is properly configured to support TLS session resumption and is compatible with the client settings.

3. **Use Active Mode**: If passive mode is causing issues, try switching to active mode.

4. **Update Library**: Ensure you are using the latest version of the FTPS client library.

5. **Check Network Configuration**: Ensure that firewalls and network settings allow the necessary ports for the FTPS data connection.

Here’s a more detailed version of the code with logging:

```java
import org.apache.commons.net.ftp.FTPSClient;
import org.apache.commons.net.PrintCommandListener;
import java.io.PrintWriter;

public class FTPSExample {
    public static void main(String[] args) {
        FTPSClient ftpsClient = new FTPSClient("TLS", true);
        
        try {
            ftpsClient.addProtocolCommandListener(new PrintCommandListener(new PrintWriter(System.out), true));
            ftpsClient.connect("ftp.example.com");
            ftpsClient.login("username", "password");
            
            ftpsClient.execPBSZ(0);
            ftpsClient.execPROT("P");
            ftpsClient.setEnabledProtocols(new String[]{"TLSv1.2"});
            ftpsClient.enterLocalPassiveMode();
            ftpsClient.setBufferSize(1024 * 1024);
            ftpsClient.setDataTimeout(30000);
            
            // Ensure file transfer type is set
            ftpsClient.setFileType(FTPSClient.BINARY_FILE_TYPE);
            
            // Test file upload
            try (InputStream input = new FileInputStream("localTestOutput.txt")) {
                boolean success = ftpsClient.storeFile("remoteTestOutput.txt", input);
                if (success) {
                    System.out.println("File uploaded successfully.");
                } else {
                    System.out.println("File upload failed.");
                }
            }
            
            ftpsClient.logout();
        } catch (IOException e) {
            e.printStackTrace();
        } finally {
            try {
                if (ftpsClient.isConnected()) {
                    ftpsClient.disconnect();
                }
            } catch (IOException e) {
                e.printStackTrace();
            }
        }
    }
}
```

### Additional Troubleshooting Steps:

1. **Switch to Active Mode**:
   ```java
   ftpsClient.enterLocalActiveMode();
   ```

2. **Server-Side Logs**:
   - Check the server-side logs for more details on why the data connection is failing.

3. **Firewall and Network Configuration**:
   - Ensure that the firewall or NAT settings on the client and server sides are not blocking the necessary ports for passive mode.

4. **Test with Different Clients**:
   - Try using another FTPS client like FileZilla to see if the issue is specific to your client configuration.

5. **TLS Configuration**:
   - Ensure that both the server and client support the same TLS versions and configurations.

If these steps do not resolve the issue, it might be necessary to consult the server's documentation or support team for further assistance.

**Comment by basilwong** [comment]
Given the detailed information and logs, it seems like the FTPS client is correctly configured, but the server is not resuming the TLS session for the data connection. Here are a few additional steps to try:

1. **Explicitly Enable Session Resumption**:
   - Some FTPS clients require additional configuration to explicitly enable TLS session resumption. Check if the Apache Commons Net library has settings related to session resumption that you need to enable.

2. **Set SSL Parameters**:
   - Configure SSL parameters to ensure the client is set up for proper TLS session handling.

Here’s how you can configure SSL parameters and enable session resumption:

```java
import org.apache.commons.net.ftp.FTPSClient;
import org.apache.commons.net.PrintCommandListener;
import java.io.PrintWriter;
import java.io.InputStream;
import java.io.FileInputStream;
import java.io.IOException;
import javax.net.ssl.SSLContext;
import javax.net.ssl.SSLSocketFactory;
import javax.net.ssl.SSLSessionContext;

public class FTPSExample {
    public static void main(String[] args) {
        FTPSClient ftpsClient = new FTPSClient("TLS", true);
        
        try {
            // Enable detailed logging
            ftpsClient.addProtocolCommandListener(new PrintCommandListener(new PrintWriter(System.out), true));
            
            // Set SSL context and session cache size
            SSLContext sslContext = SSLContext.getInstance("TLS");
            sslContext.init(null, null, null);
            SSLSessionContext sslSessionContext = sslContext.getClientSessionContext();
            sslSessionContext.setSessionCacheSize(1000);
            
            SSLSocketFactory socketFactory = sslContext.getSocketFactory();
            ftpsClient.setSocketFactory(socketFactory);

            // Connect and login
            ftpsClient.connect("ftp.example.com");
            ftpsClient.login("username", "password");
            
            ftpsClient.execPBSZ(0);
            ftpsClient.execPROT("P");
            ftpsClient.setEnabledProtocols(new String[]{"TLSv1.2"});
            ftpsClient.enterLocalPassiveMode();
            ftpsClient.setBufferSize(1024 * 1024);
            ftpsClient.setDataTimeout(30000);
            
            // Ensure file transfer type is set
            ftpsClient.setFileType(FTPSClient.BINARY_FILE_TYPE);
            
            // Test file upload
            try (InputStream input = new FileInputStream("localTestOutput.txt")) {
                boolean success = ftpsClient.storeFile("remoteTestOutput.txt", input);
                if (success) {
                    System.out.println("File uploaded successfully.");
                } else {
                    System.out.println("File upload failed.");
                }
            }
            
            ftpsClient.logout();
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            try {
                if (ftpsClient.isConnected()) {
                    ftpsClient.disconnect();
                }
            } catch (IOException e) {
                e.printStackTrace();
            }
        }
    }
}
```

### Additional Considerations:

1. **Compatibility with FileZilla Server**:
   - FileZilla Server might have specific settings that affect TLS session resumption. Ensure that session resumption is enabled and correctly configured on the server side.

2. **Debugging with Other Libraries**:
   - As a debugging step, consider using another Java library for FTPS, such as the `FTPClient` from `Apache Mina`. This might help isolate whether the issue is with the `Apache Commons Net` library or the server.

3. **Server Settings**:
   - Double-check the FileZilla server settings related to TLS/SSL. Ensure that the `Force PROT P` setting is enabled and that the passive port range is correctly configured.

If the problem persists, providing additional server logs and configuration settings might help identify the root cause.
